name: CI
on: push
jobs:
  build-compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
        working-directory: packages/compiler
      - run: yarn build
        working-directory: packages/compiler
  test-compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
        working-directory: packages/compiler
      - run: yarn test
        working-directory: packages/compiler
